### ISSUE TITLE
example server crash - dummyjob test

### ISSUE THREAD

**Issue by foreveremain** [warownia1/pyBioAS#26]
Observed on both dev(13f3487bef8b2a7845cc53ba10747f12ecc16320) and master(51d7ee878fcbc7ba5a32d911eb2d622d45a48f20)

1. install example server, initdb, and start server, scheduler, worker.
2. Via pybioas-client:
''LANG=en_GB.UTF-8 python client.py submit PyDummy number=913 message="requirements.txt" return_code=3 error="foo"''

See output:

Server
^C(pybioas) (pybioas) ls30857:testserver jprocter$ python manage.py server
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 143-332-217
127.0.0.1 - - [25/Jul/2016 15:05:11] "POST /service/PyDummy/form HTTP/1.1" 202 -

Scheduler
(pybioas) (pybioas) ls30857:testserver jprocter$ python manage.py scheduler
25 Jul 15:04:52 Scheduler:PollThread INFO: Scheduler starts watching database.
25 Jul 15:04:52 Scheduler:CollectorThread INFO: Scheduler starts collecting tasks from worker.
25 Jul 15:04:52 Scheduler:PollThread INFO: Can't establish connection to worker. Retry in 5 seconds.
25 Jul 15:04:52 Scheduler:CollectorThread INFO: Can't establish connection to worker. Retry in 5 seconds.
25 Jul 15:04:57 Scheduler:CollectorThread INFO: Can't establish connection to worker. Retry in 5 seconds.
25 Jul 15:04:57 Scheduler:PollThread INFO: Can't establish connection to worker. Retry in 5 seconds.
25 Jul 15:04:57 Scheduler:CollectorThread INFO: Connected to worker.
25 Jul 15:04:57 Scheduler:PollThread INFO: Connected to worker.
Exception in thread CollectorThread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jprocter/virtualenv/pybioas/lib/python3.5/site-packages/PyBioAS-0.0.dev1-py3.5.egg/pybioas/scheduler/scheduler.py", line 125, in collector_loop
    result = task.deferred_result.result
  File "/Users/jprocter/virtualenv/pybioas/lib/python3.5/site-packages/PyBioAS-0.0.dev1-py3.5.egg/pybioas/scheduler/task_queue/deferred_result.py", line 63, in result
    data = utils.recv_json(client_socket)
  File "/Users/jprocter/virtualenv/pybioas/lib/python3.5/site-packages/PyBioAS-0.0.dev1-py3.5.egg/pybioas/scheduler/task_queue/utils.py", line 21, in recv_json
    return json.loads(content)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 65296 (char 65295)

Worker:
(pybioas) (pybioas) ls30857:testserver jprocter$ python manage.py worker
25 Jul 15:04:55 TaskQueue INFO: Ready to accept connections on localhost:9090
25 Jul 15:04:57 TaskQueue INFO: Received connection from ('127.0.0.1', 62467)
25 Jul 15:04:57 TaskQueue INFO: Received connection from ('127.0.0.1', 62468)
25 Jul 15:05:12 TaskQueue INFO: Received connection from ('127.0.0.1', 62471)
25 Jul 15:05:12 TaskQueue INFO: Created job <Job> bfdbe68a7d8942fba1a466bc75a4507f - QUEUED
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jprocter/virtualenv/pybioas/lib/python3.5/site-packages/PyBioAS-0.0.dev1-py3.5.egg/pybioas/scheduler/task_queue/task_queue.py", line 228, in _serve_client
    conn.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected

[Logs.zip](https://github.com/warownia1/pyBioAS/files/381670/Logs.zip)

**Comment by warownia1** [comment]
Possible cause (not confirmed):
Single packet is limited to 2^16 bytes and is trimmed after that point. String starting at 65296 which is almost 2^16 is unterminated because the rest of message is lost.
